# Site settings
title: Trigger My Idea
email: triggermyidea@gmail.com
url: https://var7.github.io/tmi-website
description: "Trigger My Idea is a platform for budding entrepreneurial minds to share their ideas, meet like-minded students, brainstorm and innovate."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 55B8ED #0F8DDB #18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: triggermyidea
  location: Location
  social: Around the Web
  credits: Contact

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url:
  - title: github
    url: http://github.com/var7

# Postal address (add as many lines as necessary)
address:
  - line: Hyderabad, India

# Credits content
credits: triggermyidea@gmail.com

# Build settings
markdown: kramdown
permalink: pretty
